version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - PUBLIC_API_URL
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=3000

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - tempnote_data:/app/data
    environment:
      - DB_PATH=/app/data/tempnote.db
      - PORT=8080

volumes:
  tempnote_data:
